add cloud function build+deploy to gha

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,6 +8,8 @@ env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
   REPO_NAME: ${{ github.event.repository.name }}
+  SCW_REGION: fr-par
+  SCW_FUNCTION_DEPLOY_TIMEOUT: 600
 
 jobs:
   build-dev-image:
@@ -95,6 +97,83 @@ jobs:
           echo "$LUIGI_ENV" > .luigi_env
           echo "$POSTGRES_ENV" > .postgres_env
           make ci-pyright
+  build-cloud-function:
+    runs-on: ubuntu-latest
+    needs: build-dev-image
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ env.REPO_NAME }}_dev
+          path: /tmp
+      - name: Load image into Docker
+        run: |
+          docker load --input /tmp/${{ env.REPO_NAME }}_dev.tar
+          docker image ls -a
+      - name: Build serverless function zip
+        run: |
+          make build-serverless-function
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: cloud_function_zip
+          path: ./cloud_function.zip
+  update-cloud-function:
+    runs-on: ubuntu-latest
+    env:
+      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
+      SCW_FUNCTION_ID: ${{ secrets.SCW_FUNCTION_ID }}
+    needs:
+      - run-pytest
+      - run-pyright
+      - build-cloud-function
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: cloud_function_zip
+          path: /tmp
+      - name: Upload function zip
+        run: |
+          ARCHIVE_SIZE=$(wc -c < /tmp/cloud_function.zip)
+
+          PRESIGNED_URL=$(curl -X GET -H "X-Auth-Token: $SCW_SECRET_KEY" \
+          "https://api.scaleway.com/functions/v1beta1/regions/${{ env.SCW_REGION }}/functions/$SCW_FUNCTION_ID/upload-url?content_length=$ARCHIVE_SIZE" | jq ."url")
+
+          curl -H "Content-Type: application/octet-stream" --upload-file /tmp/cloud_function.zip \
+          -H "Content-Length: $ARCHIVE_SIZE" $PRESIGNED_URL
+      - name: Deploy function
+        run: |
+          curl -X POST \
+            -H "X-Auth-Token: $SCW_SECRET_KEY" \
+            -H "Content-Type: application/json" \
+            -d '{}' \
+            "https://api.scaleway.com/functions/v1beta1/regions/${{ env.SCW_REGION }}/functions/$SCW_FUNCTION_ID/deploy"
+      - name: Check function status and wait until ready
+        run: |
+          LOOP_START=$EPOCHSECONDS
+          while :
+          do
+            FUNCTION_STATUS=$(curl -X GET \
+              -H "X-Auth-Token: $SCW_SECRET_KEY" \
+              "https://api.scaleway.com/functions/v1beta1/regions/${{ env.SCW_REGION }}/functions/$SCW_FUNCTION_ID" | jq .status)
+            if [[ "$FUNCTION_STATUS" == "ready" ]]; then
+              echo "Function has status ready and seems to be deployed successfully."
+              exit 0
+            fi
+
+            # exit with failure if timeout
+            if (( EPOCHSECONDS - LOOP_START > $SCW_FUNCTION_DEPLOY_TIMEOUT )); then
+              echo "Timed out while deploying function"
+              exit 1
+            fi
+
+            sleep 10
+          done
   build-e2e-test-and-push-image:
     runs-on: ubuntu-latest
     needs:
